# Uncomment this line to define a global platform for your project
use_frameworks!
platform :ios, '8.0'

target 'keyboardTest' do
  pod 'KGFloatingDrawer', :path => "../"
end

target 'keyboardTestTests' do

end
